spring:
  config.activate.on-profile: dev-gcp
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    locations: classpath:/db/migration, classpath:/db/privileges

altinn:
  uri: https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc

no.nav.security.jwt.issuer:
  aad:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    cookie_name: isso-idtoken
    accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}
