server.servlet.context-path: /altinn-meldinger-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

spring.profiles.active: local

---

spring.config.activate.on-profile: local
wiremock.port: 8081

altinn:
  uri: "http://localhost:${wiremock.port}/altinn"
  brukernavn: brukernavn
  passord: passord


---

spring.config.activate.on-profile: dev-gcp

altinn:
  uri: https://tt02.altinn.no


---

spring.config.activate.on-profile: prod-gcp

altinn:
  uri: https://altinn.no

