spring:
  config.activate.on-profile: prod-gcp
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    locations: classpath:/db/migration, classpath:/db/privileges

altinn:
  uri: https://www.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc

dokarkiv:
  uri: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost

pdfgen:
  uri: https://altinn-meldinger-dokgen.intern.nav.no/template/arbeidsgiver-altinnmelding-melding/create-pdf

groupid: 53e6bb70-00e3-498a-9a69-1466e9a22d39

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      cookie_name: isso-idtoken
      accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}, 05b20497-e175-431e-8324-c19354d71355

  client.registration.altinnmelding:
    token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
    grant-type: client_credentials
    scope: 162b3255-2f72-4399-8f7a-244add9ffaac/.default
    authentication:
      client-id: ${AZURE_APP_CLIENT_ID}
      client-auth-method: client_secret_basic
      client-secret: ${AZURE_APP_CLIENT_SECRET}