spring:
  config.activate.on-profile: dev-gcp
  h2.console:
    enabled: true
    settings:
      web-allow-others: true
    path: /h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

altinn:
  uri: https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
