server.servlet.context-path: /altinn-meldinger

spring.profiles.active: local

---

spring.config.activate.on-profile: local
wiremock.port: 8081

altinn:
  uri: "http://localhost:${wiremock.port}/altinn"
  brukernavn: brukernavn
  passord: passord
