server.servlet.context-path: /altinn-meldinger-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

utsending:
  altinn.scheduler:
    lockAtMostFor: 300000
    lockAtLeastFor: 2000
  dokarkiv.scheduler:
    lockAtMostFor: 300000
    lockAtLeastFor: 2000

spring.profiles.active: local
