spring:
  config.activate.on-profile: dev-gcp
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/altinn-meldinger-db"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

altinn:
  uri: https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
