spring:
  config.activate.on-profile: dev-gcp
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    locations: classpath:/db/migration, classpath:/db/privileges

altinn:
  uri: https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
dokarkiv:
  uri: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost


no.nav.security.jwt.client.registration.altinnmelding:
  token-endpoint-url: todo
  grant-type: todo
  scope: 9todo
  authentication:
    client-id: todo
    client-auth-method: todo
    client-secret: todo