spring:
  config.activate.on-profile: prod-gcp
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

altinn:
  uri: https://www.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc

