spring:
  config.activate.on-profile: prod-gcp
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

altinn:
  uri: https://www.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc

