spring:
  config.activate.on-profile: dev-gcp
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    locations: classpath:/db/migration, classpath:/db/privileges

altinn:
  uri: https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
dokarkiv:
  uri: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost

pdfgen:
  uri: "uri"

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      cookie_name: isso-idtoken
      accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

  client.registration.altinnmelding:
    token-endpoint-url: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
    grant-type: client_credentials
    scope: 972814f3-8bdf-44f8-a191-c2ed00020b54/.default
    authentication:
      client-id: ${AZURE_APP_CLIENT_ID}
      client-auth-method: client_secret_basic
      client-secret: ${AZURE_APP_CLIENT_SECRET}