apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: altinn-meldinger-api
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: docker.pkg.github.com/navikt/altinn-meldinger-api/altinn-meldinger-api:0b293a1bf86f426e2b53f94f113f024656756d53
    team: arbeidsgiver
    port: 8080
    ingresses:
        - https://arbeidsgiver.dev.intern.nav.no/altinn-meldinger-api
    liveness:
        path: /altinn-meldinger-api/internal/healthcheck
        initialDelay: 120
    readiness:
        path: /altinn-meldinger-api/internal/healthcheck
        initialDelay: 120
    prometheus:
        enabled: true
        path: /altinn-meldinger-api/internal/actuator/prometheus
    gcp:
        sqlInstances:
            - name: altinn-meldinger-api
              type: POSTGRES_12
              databases:
                  - name: altinn-meldinger-db
                    envVarPrefix: DATABASE
    env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev-gcp
    envFrom:
        - secret: altinn-meldinger-api-secrets
    accessPolicy:
        outbound:
            external:
                - host: tt02.altinn.no
