apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: altinn-meldinger-api
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ version }}
    team: arbeidsgiver
    port: 8080
    ingresses:
        - https://arbeidsgiver.dev.intern.nav.no/altinn-meldinger-api
    liveness:
        path: /altinn-meldinger-api/internal/healthcheck
        initialDelay: 60
    readiness:
        path: /altinn-meldinger-api/internal/healthcheck
        initialDelay: 60
    prometheus:
        enabled: true
        path: /altinn-meldinger-api/internal/actuator/prometheus
    gcp:
        sqlInstances:
            - name: altinn-meldinger-api
              type: POSTGRES_12
              databases:
                  - name: altinn-meldinger-db
                    envVarPrefix: DATABASE
    env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev-gcp
        - name: ENKELUTSENDING_ID
          value: enkelutsending-id-test-2
    envFrom:
        - secret: altinn-meldinger-api-secrets
        - secret: altinn-meldinger-api-enkelutsending-orgnrs
        - secret: altinn-meldinger-api-enkelutsending-melding
    accessPolicy:
        outbound:
            external:
                - host: tt02.altinn.no
                - host: dokarkiv.dev-fss-pub.nais.io
                - host: login.microsoftonline.com
                - host: altinn-meldinger-dokgen.dev.intern.nav.no
        inbound:
            rules:
                - application: altinn-meldinger-web
    azure:
        application:
            enabled: true
            tenant: trygdeetaten.no
    webproxy: false
