apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: altinn-meldinger-api
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ version }}
    team: arbeidsgiver
    port: 8080
    ingresses:
        - https://arbeidsgiver.dev.intern.nav.no/altinn-meldinger-api
    liveness:
        path: /altinn-meldinger-api/internal/healthcheck
        initialDelay: 40
    readiness:
        path: /altinn-meldinger-api/internal/healthcheck
        initialDelay: 40
    prometheus:
        enabled: true
        path: /altinn-meldinger-api/internal/actuator/prometheus
    env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev-gcp
    envFrom:
        - secret: altinn-meldinger-api-secrets
        - secret: altinn-meldinger-api-testsending
    accessPolicy:
        outbound:
            external:
                - host: tt02.altinn.no
