apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: altinn-meldinger-api
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: docker.pkg.github.com/navikt/altinn-meldinger-api/altinn-meldinger-api:955de4147d446c8cabf3ff3a2bc256d31b8de0e6
    team: arbeidsgiver
    port: 8080
    ingresses:
        - https://arbeidsgiver.dev.intern.nav.no/altinn-meldinger-api
    liveness:
        path: /altinn-meldinger-api/internal/healthcheck
        initialDelay: 40
    readiness:
        path: /altinn-meldinger-api/internal/healthcheck
        initialDelay: 40
    prometheus:
        enabled: true
        path: /altinn-meldinger-api/internal/actuator/prometheus
    env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev-gcp
    envFrom:
        - secret: altinn-meldinger-api-secrets
