apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: altinn-meldinger-api
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    image: {{ version }}
    team: arbeidsgiver
    port: 8080
    ingresses:
        - https://arbeidsgiver.intern.nav.no/altinn-meldinger-api
    liveness:
        path: /altinn-meldinger-api/internal/healthcheck
        initialDelay: 60
    readiness:
        path: /altinn-meldinger-api/internal/healthcheck
        initialDelay: 60
    prometheus:
        enabled: true
        path: /altinn-meldinger-api/internal/actuator/prometheus
    gcp:
        sqlInstances:
            - name: altinn-meldinger-api
              type: POSTGRES_12
              databases:
                  - name: altinn-meldinger-db
                    envVarPrefix: DATABASE
    env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod-gcp
    envFrom:
        - secret: altinn-meldinger-api-secrets
    accessPolicy:
        outbound:
            external:
                - host: www.altinn.no
                - host: altinn.no
    azure:
        application:
            enabled: true
            tenant: nav.no
    webproxy: false
